### ISSUE TITLE
ini template needs to work out-of-the-box

### ISSUE THREAD

**Issue by pryrt** [pryrt/pyscFilteredViewer#5]
(Meta Chuh's [suggestion 2](https://notepad-plus-plus.org/community/topic/16997/rfc-beta-testers-wanted-pyscfilteredviewer/16)):

as it is a completely new product, it’s imperative to ensure an immediate, easy start for any new user, eg. by delivering prebuilt, functioning configuration files (pyscFilteredViewer.ini) to attract people to a new application.

a default ini should be fully working, without relying that a new user understands what to do, in order to ensure a high acceptance count. (unless it’s an already huge product, like apache, where the devs can say: everyone uses it, so learn it or leave it 😉)

a distributed ini example would be:

    [PHPFile]                                   ;   => this is the name of the section; it must be unique.  Typically, based on the language
    Extension=.php                              ;   => space-separated list of filename extensions, including the period.
    Language=PHP                                ;   => this is the name of the language (from Notepad++'s perspective): for a UDL, use your "UserName" from the UDL dialog
    Command=C:\usr\local\bin\phpysc.exe "%1"    ;   => this is the filter command; %1 is the name of the active file/buffer; the command must result in the HTML being dumped to STDOUT

or even better, an ini using a working preview-ini.bat or exe which is already deployed from the pyscFilteredViewer folder in the zip, as it would always be in `%AppData%\Notepad++\plugins\config\PythonScript\scripts\pyscFilteredViewer` instead of a non predictable location on each user’s unique setup as example.

**Comment by MetaChuh** [comment]
@pryrt 
ps: you can address me as @MetaChuh at github, this way i'll get a notification and will not miss out on anything.

**Comment by MetaChuh** [comment]
pps: i won't consider it a bug though, as there's nothing wrong with the code (still no crash for me), and only related to the manual and adding a distributed, fully featured sample .ini

**Comment by MetaChuh** [comment]
👍
